version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=UTC
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  n8n:
    container_name: n8n
    image: n8nio/n8n:latest
    restart: always
    volumes:
      - ./n8n:/home/node/.n8n # n8n data
      - ./n8n/log:/var/log/n8n # n8n log
      - ./n8n/ssl:/home/node/.n8n/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
    environment:
      - DB_TYPE=${DB_TYPE}
      - DB_POSTGRESDB_HOST=${DB_POSTGRESDB_HOST}
      - DB_POSTGRESDB_PORT=${DB_POSTGRESDB_PORT}
      - DB_POSTGRESDB_DATABASE=${DB_POSTGRESDB_DATABASE}
      - DB_POSTGRESDB_USER=${DB_POSTGRESDB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_POSTGRESDB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=${N8N_BASIC_AUTH_ACTIVE}
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - TZ=UTC
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx_n8n
    restart: unless-stopped
    ports:
      - "443:443" # public port
      - "80:80" # public port
    depends_on:
      - n8n
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d # configuration in default.conf
      - ./nginx/ssl:/etc/nginx/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
      - ./nginx/html:/var/www/html # static html web for example
      - ./nginx/log:/var/log/nginx/
    environment:
      - TZ=UTC

