version: '3'

services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - TZ=UTC
    volumes:
      - odoo18-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - TZ=UTC
    volumes:
      - odoo18-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons

volumes:
  odoo18-db-data:
  odoo18-web-data: