version: '3.8'

services:
  mail:
    image: nginx:latest
    container_name: mail
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mail.rule=Host(`mail.dotcon.vn`)"
      - "traefik.http.routers.mail.entrypoints=web,websecure"
      - "traefik.http.routers.mail.tls.certresolver=letsencrypt"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d # configuration in default.conf
      - ./nginx/html:/var/www/html # static html web for example
      - ./nginx/log:/var/log/nginx/ # log data
    networks:
      - web

networks:
  web:
    external: true
