
services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900" 
      - "5900:5900" 
    environment:
      SE_VNC_NO_PASSWORD: 1
      SE_NO_VNC_PORT: 7900
      # VNC_PASSWORD: secret  # Mật khẩu noVNC

  selenium-chrome:
    image: selenium/standalone-chrome:4.23.0-20240727
    shm_size: 2gb
    ports:
      - "4444:4444"    # Cổng cho Selenium Grid
      - "7900:7900"    # Cổng cho noVNC
      - "5900:5900"    # Cổng cho VNC
    environment:
      SE_NO_VNC_PORT: 7900
      SE_VNC_PORT: 5900
      SE_VNC_NO_PASSWORD: 1   # Không cần mật khẩu
      # VNC_PASSWORD: secret  # Mật khẩu noVNC

  selenium-firefox:
    image: selenium/standalone-firefox:4.23.0-20240727
    shm_size: 2gb
    ports:
      - "4445:4444"    # Cổng cho Selenium Grid
      - "7901:7900"    # Cổng cho noVNC
    environment:
      SE_NO_VNC_PORT: 7900
      VNC_PASSWORD: secret  # Mật khẩu noVNC