version: '3.7'

services:
  db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: justdice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@2024
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - mysql-phpmyadmin


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: admin@2024
    ports:
      - "8080:80"
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  mysql_data: