version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: justdice
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@2024
    volumes:
      - ./mysql_data:/var/lib/mysql
    # ports:
    #   - "3306:3306"
    expose:
      - 3306
    networks:
      - mysql-phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: admin@2024
    ports:
      - "8080:80"
    networks:
      - mysql-phpmyadmin

  justdice:
    image: justdice:latest
    container_name: justdice
    restart: unless-stopped
    ports:
      - "3000:3000"
    networks:
      - mysql-phpmyadmin
    environment:
      DB_HOST: mysqldb 
      DB_PORT: 3306
    volumes:
      - ./config/.env:/app/.env:ro
    depends_on:
      - mysqldb

networks:
  mysql-phpmyadmin:

volumes:
  mysql_data: