services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@2024
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: admin@2024
    ports:
      - "8081:80"

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80" # public port
      - "443:443" # public port
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d # configuration in default.conf
      - ./nginx/ssl:/etc/nginx/ssl # Secure Sockets Layer (SSL) file: server-sample.crt, server-sample.key
      - ./nginx/html:/var/www/html # static html web for example
      - ./nginx/log:/var/log/nginx/

  ticket:
    image: ticket:latest
    container_name: ticket
    restart: always
    depends_on:
      - mysqldb
    # ports:
    #   - "8080:8080"
    expose:
      - 8080
    volumes:
      - ./logs:/logs
      - ./src/main/resources/application.properties:/app/src/main/resources/application.properties

volumes:
  mysql_data:
