services:
  mysqldb:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ticket
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin@2024
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - mysqldb
    environment:
      PMA_HOST: mysqldb
      MYSQL_ROOT_PASSWORD: admin@2024
    ports:
      - "8081:80"

volumes:
  mysql_data:
