version: '3'
services:
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
      - "7900:7900" 
    restart : always
    environment:
      SE_VNC_NO_PASSWORD: 1
      SE_NO_VNC_PORT: 7900
      VNC_PASSWORD: secret  # Mật khẩu noVNC

  seleniumcapture:
    image: seleniumcapture:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    restart : always