apiVersion: v1
kind: Service
metadata:
  name: {{ include "py-chat.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "py-chat.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5000
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app.kubernetes.io/name: {{ include "py-chat.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
