api:
  dashboard: true
  insecure: true  # true: Cho phép truy cập dashboard không cần authentication
  debug: true

auth:
  basic:
    users:
      - "admin:$2b$12$Ce10/4Zwky/2.y4gBcWdQeMVMFDlOVSJaPAogegzC6fpFJVZb/zeC" # admin:admin
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    exposedByDefault: false
  # docker:
  #   endpoint: "unix:///var/run/docker.sock"
  #   exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: admin@dotcon.vn
      storage: /letsencrypt/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web


experimental:
  plugins:
    fail2ban:
      moduleName: "github.com/tomMoulard/fail2ban"
      version: "v0.8.3"