version: "3"
services:
  postgresql:
    image: postgres:latest
    user: root
    networks:
      - postgres_network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgrespwd
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    restart: always # run as a service
  pgadmin:
    image: dpage/pgadmin4:latest
    user: root
    networks:
      - postgres_network
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadminpwd
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
      # - ./pgadmin/pgadmin4:/pgadmin4
    depends_on:
      - postgresql
networks:
  postgres_network:
    driver: bridge